if(EMSCRIPTEN)
  add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/emscripten)
elseif(WINDOWS)
  if(ARCH_64)
    add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/windows64)
  else()
    add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/windows32)
  endif()
elseif(APPLE)
  if(IOS)
    add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/ios)
  elseif(TVOS)
    add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/appletv)
  else()
    add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/macos)
  endif()
elseif(UNIX AND NOT APPLE AND NOT ANDROID)
  if(LINUX)
    add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/linux)
  elseif(UNIX)
    add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/unix)
  endif()
elseif(ANDROID)
  add_subdirectory(${CMAKE_SOURCE_DIR}/cmake/android)
endif()


